version: "3"

services:
  web:
    image: ngser/ussd_redevance:latest
    container_name: ussd_redevance
    build: .
    depends_on:
      - database
      - redis
    ports:
      - "9002:3000"
    volumes:
      - .:/home/ngser/app
    env_file:
      - .env
    environment:
      - DB_USERNAME=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
  database:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - "9003:5432"
    volumes:
      - "${APPLICATION_DATA_REPOSITORY_LINK}:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  redis:
    image: redis:6.2.1-alpine
    restart: always
